#!/usr/bin/env python3
"""
2024 Regression Harness for Buckman Wellfield Pipeline

This script runs the complete Buckman wellfield depletion pipeline using frozen 2024
inputs and compares outputs against expected values. It provides a high-confidence
verification that code changes haven't broken the compliance-critical calculations.

Scientific Basis:
- Uses known-good 2024 data as regression baseline
- Cell-by-cell comparison with tolerance-based matching
- SHA-256 hash verification ensures input integrity

Assumptions:
1. Frozen inputs in validation/2024/inputs/ are unmodified
2. Expected outputs in validation/2024/expected_outputs/ are validated
3. tolerances.yaml defines acceptance criteria per table
4. All pipeline dependencies (Wine, MODFLOW, etc.) are installed

Usage:
    python3 run_regression_2024.py           # Full regression test
    python3 run_regression_2024.py --verify  # Hash verification only
    python3 run_regression_2024.py --compare # Compare only (skip pipeline)

Returns:
    Exit code 0: All tests passed
    Exit code 1: One or more tests failed
"""

import argparse
import hashlib
import json
import os
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from typing import Any

import pandas as pd
import yaml

# =============================================================================
# CONFIGURATION
# =============================================================================

# Base directories (relative to this script's location)
SCRIPT_DIR = Path(__file__).parent.resolve()
PROJECT_ROOT = SCRIPT_DIR.parent.parent  # validation/2024/ -> project root

INPUTS_DIR = SCRIPT_DIR / "inputs"
EXPECTED_DIR = SCRIPT_DIR / "expected_outputs"
TOLERANCES_FILE = SCRIPT_DIR / "tolerances.yaml"

# Pipeline output locations (generated by step4)
PIPELINE_OUTPUT_DIR = PROJECT_ROOT / "output" / "depletion"


# =============================================================================
# HELPER FUNCTIONS
# =============================================================================

def print_header(title: str) -> None:
    """Print a formatted section header."""
    print()
    print("=" * 70)
    print(title)
    print("=" * 70)


def print_error(what_failed: str, location: str, actual: str, expected: str, context: str) -> None:
    """Print forensic-quality error message."""
    print(f"ERROR: {what_failed}")
    print(f"  Location: {location}")
    print(f"  Actual: {actual}")
    print(f"  Expected: {expected}")
    print(f"  Physical context: {context}")


# =============================================================================
# HASH VERIFICATION (Step 1)
# =============================================================================

def compute_sha256(file_path: Path) -> str:
    """Compute SHA-256 hash of a file."""
    sha256_hash = hashlib.sha256()
    with open(file_path, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            sha256_hash.update(chunk)
    return sha256_hash.hexdigest()


def verify_input_hashes() -> bool:
    """
    Verify SHA-256 hashes of frozen input files match hashes.json.

    Returns:
        True if all hashes match, False otherwise
    """
    print_header("STEP 1: VERIFY INPUT HASHES")

    hashes_file = INPUTS_DIR / "hashes.json"
    if not hashes_file.exists():
        print_error(
            "hashes.json not found",
            str(hashes_file),
            "File missing",
            "hashes.json with SHA-256 hashes",
            "Run validation setup first"
        )
        return False

    with open(hashes_file) as f:
        hash_data = json.load(f)

    files_info = hash_data.get("files", {})
    all_passed = True

    print(f"Checking {len(files_info)} frozen input file(s)...")
    print()

    for filename, info in files_info.items():
        file_path = INPUTS_DIR / filename
        expected_hash = info["sha256"]
        expected_size = info["size_bytes"]

        if not file_path.exists():
            print(f"  FAIL: {filename}")
            print("        File not found")
            all_passed = False
            continue

        actual_size = file_path.stat().st_size
        if actual_size != expected_size:
            print(f"  FAIL: {filename}")
            print(f"        Size mismatch: {actual_size} bytes (expected {expected_size})")
            all_passed = False
            continue

        actual_hash = compute_sha256(file_path)
        if actual_hash != expected_hash:
            print(f"  FAIL: {filename}")
            print("        Hash mismatch!")
            print(f"        Expected: {expected_hash}")
            print(f"        Actual:   {actual_hash}")
            all_passed = False
            continue

        print(f"  PASS: {filename} ({actual_size:,} bytes)")

    print()
    if all_passed:
        print("All input hashes verified.")
    else:
        print("INPUT VERIFICATION FAILED - frozen inputs may have been modified!")

    return all_passed


# =============================================================================
# PIPELINE EXECUTION (Step 2)
# =============================================================================

def run_pipeline_2024() -> bool:
    """
    Execute the complete 2024 pipeline: steps 1-4.

    Pipeline order:
    1. step1_ingest_buckman_data.py --year 2024
    2. step2_update_modflow.py --year 2024
    3. step3_run_modflow.sh --year 2024 (includes sfmodflx_2245.exe)
    4. step4_generate_depletion_tables.py --year 2024

    Returns:
        True if pipeline completed successfully, False otherwise
    """
    print_header("STEP 2: RUN 2024 PIPELINE")

    os.chdir(PROJECT_ROOT)
    print(f"Working directory: {PROJECT_ROOT}")
    print()

    # Pipeline steps
    steps = [
        ("Step 1: Ingest data", ["python3", "step1_ingest_buckman_data.py", "--year", "2024"]),
        ("Step 2: Update MODFLOW", ["python3", "step2_update_modflow.py", "--year", "2024"]),
        ("Step 3: Run MODFLOW", ["bash", "step3_run_modflow.sh", "--year", "2024"]),
        ("Step 4: Generate tables", ["python3", "step4_generate_depletion_tables.py", "--year", "2024"]),
    ]

    for step_name, cmd in steps:
        print(f"\n--- {step_name} ---")
        print(f"Command: {' '.join(cmd)}")
        print()

        try:
            result = subprocess.run(
                cmd,
                capture_output=False,  # Let output stream to console
                text=True,
                timeout=3600,  # 1 hour timeout for MODFLOW
                cwd=PROJECT_ROOT
            )

            if result.returncode != 0:
                print_error(
                    f"{step_name} failed",
                    str(PROJECT_ROOT),
                    f"Exit code {result.returncode}",
                    "Exit code 0",
                    "Check step output above for details"
                )
                return False

            print(f"{step_name}: COMPLETED")

        except subprocess.TimeoutExpired:
            print_error(
                f"{step_name} timed out",
                str(PROJECT_ROOT),
                "Exceeded 1 hour timeout",
                "Completion within timeout",
                "MODFLOW may be stuck or system is overloaded"
            )
            return False

        except FileNotFoundError as e:
            print_error(
                f"Command not found: {step_name}",
                str(PROJECT_ROOT),
                str(e),
                "Executable in PATH",
                "Check that python3, bash, and dependencies are installed"
            )
            return False

    print()
    print("Pipeline completed successfully.")
    return True


# =============================================================================
# TABLE COMPARISON (Step 3)
# =============================================================================

def load_tolerances() -> dict[str, Any]:
    """Load tolerance definitions from YAML file."""
    with open(TOLERANCES_FILE) as f:
        return yaml.safe_load(f)


def values_match(actual: float, expected: float, tol_config: dict) -> tuple[bool, str]:
    """
    Check if two values match within tolerance.

    Args:
        actual: Computed value
        expected: Expected value
        tol_config: Tolerance configuration dict

    Returns:
        (matches, reason) tuple
    """
    # Handle NaN
    if pd.isna(actual) or pd.isna(expected):
        return False, "NaN value encountered"

    abs_tol = tol_config.get("absolute_tolerance", 0.01)
    rel_tol = tol_config.get("relative_tolerance", 0.001)

    abs_diff = abs(actual - expected)

    # Absolute tolerance check
    if abs_diff <= abs_tol:
        return True, f"within absolute tolerance ({abs_diff:.6f} <= {abs_tol})"

    # Relative tolerance check (avoid division by zero)
    if expected != 0:
        rel_diff = abs_diff / abs(expected)
        if rel_diff <= rel_tol:
            return True, f"within relative tolerance ({rel_diff:.4%} <= {rel_tol:.4%})"

    return False, f"diff={abs_diff:.6f} ({abs_diff/abs(expected)*100:.2f}% of expected)" if expected != 0 else f"diff={abs_diff:.6f}"


def compare_excel_files(
    actual_path: Path,
    expected_path: Path,
    table_name: str,
    tol_config: dict
) -> dict[str, Any]:
    """
    Compare two Excel files cell-by-cell within tolerances.

    Args:
        actual_path: Path to generated Excel file
        expected_path: Path to expected Excel file
        table_name: Table identifier (e.g., "Table_1")
        tol_config: Tolerance configuration for this table

    Returns:
        Comparison results dict with status, failures, etc.
    """
    result = {
        "table": table_name,
        "status": "PASS",
        "failures": [],
        "total_cells": 0,
        "passed_cells": 0,
    }

    # Check files exist
    if not actual_path.exists():
        result["status"] = "FAIL"
        result["failures"].append(f"Generated file not found: {actual_path}")
        return result

    if not expected_path.exists():
        result["status"] = "SKIP"
        result["failures"].append(f"Expected file not found: {expected_path}")
        return result

    # Load Excel files
    try:
        actual_df = pd.read_excel(actual_path, sheet_name=0)
        expected_df = pd.read_excel(expected_path, sheet_name=0)
    except Exception as e:
        result["status"] = "FAIL"
        result["failures"].append(f"Error reading Excel files: {e}")
        return result

    # Get max_year filter if specified (for Table 5)
    max_year = tol_config.get("max_year")

    # Compare dimensions
    if actual_df.shape != expected_df.shape:
        # Try to handle year filtering for Table 5
        if max_year and "Year" in expected_df.columns:
            expected_df = expected_df[expected_df["Year"] <= max_year]
            if "Year" in actual_df.columns:
                actual_df = actual_df[actual_df["Year"] <= max_year]

        if actual_df.shape != expected_df.shape:
            result["status"] = "FAIL"
            result["failures"].append(
                f"Shape mismatch: actual {actual_df.shape} vs expected {expected_df.shape}"
            )
            return result

    # Cell-by-cell comparison
    for row_idx in range(len(expected_df)):
        for col_idx in range(len(expected_df.columns)):
            result["total_cells"] += 1

            expected_val = expected_df.iloc[row_idx, col_idx]
            actual_val = actual_df.iloc[row_idx, col_idx]

            # Skip comparison for non-numeric cells
            if not isinstance(expected_val, (int, float)):
                result["passed_cells"] += 1
                continue

            if pd.isna(expected_val) and pd.isna(actual_val):
                result["passed_cells"] += 1
                continue

            matches, reason = values_match(actual_val, expected_val, tol_config)

            if matches:
                result["passed_cells"] += 1
            else:
                result["status"] = "FAIL"
                col_name = expected_df.columns[col_idx]
                result["failures"].append(
                    f"Row {row_idx + 1}, Col '{col_name}': "
                    f"actual={actual_val:.6f}, expected={expected_val:.6f}, {reason}"
                )

    return result


def compare_tables() -> dict[str, Any]:
    """
    Compare all generated tables against expected outputs.

    Returns:
        Dict with overall status and per-table results
    """
    print_header("STEP 3: COMPARE TABLES")

    tolerances = load_tolerances()
    results = {
        "overall_status": "PASS",
        "tables": {},
    }

    # Table mapping: (generated_name, expected_name)
    table_mappings = [
        ("TABLE_3_Rio_Pojoaque_Tesuque_2024.xlsx", "Table_3_expected.xlsx", "Table_3"),
        ("TABLE_4_Rio_Grande_Otowi_2024.xlsx", "Table_4_expected.xlsx", "Table_4"),
        ("TABLE_5_La_Cienega_Springs_2024.xlsx", "Table_5_expected.xlsx", "Table_5"),
    ]

    for generated_name, expected_name, table_key in table_mappings:
        actual_path = PIPELINE_OUTPUT_DIR / generated_name
        expected_path = EXPECTED_DIR / expected_name

        tol_config = tolerances.get("tables", {}).get(table_key, {})

        print(f"\nComparing {table_key}...")
        print(f"  Generated: {actual_path}")
        print(f"  Expected:  {expected_path}")

        result = compare_excel_files(actual_path, expected_path, table_key, tol_config)
        results["tables"][table_key] = result

        if result["status"] == "PASS":
            print(f"  Status: PASS ({result['passed_cells']}/{result['total_cells']} cells)")
        elif result["status"] == "SKIP":
            print(f"  Status: SKIP - {result['failures'][0]}")
        else:
            print("  Status: FAIL")
            for failure in result["failures"][:5]:  # Show first 5 failures
                print(f"    - {failure}")
            if len(result["failures"]) > 5:
                print(f"    ... and {len(result['failures']) - 5} more failures")
            results["overall_status"] = "FAIL"

    # Also check Tables 1 and 2 (pumping data from step1)
    pumping_tables = [
        ("2024_Table_1_updated.xlsx", "Table_1_expected.xlsx", "Table_1"),
        ("2024_Table_2_output.xlsx", "Table_2_expected.xlsx", "Table_2"),
    ]

    pumping_output_dir = PROJECT_ROOT / "output" / "ingested_data"

    for generated_name, expected_name, table_key in pumping_tables:
        actual_path = pumping_output_dir / generated_name
        expected_path = EXPECTED_DIR / expected_name

        tol_config = tolerances.get("tables", {}).get(table_key, {})

        print(f"\nComparing {table_key}...")
        print(f"  Generated: {actual_path}")
        print(f"  Expected:  {expected_path}")

        result = compare_excel_files(actual_path, expected_path, table_key, tol_config)
        results["tables"][table_key] = result

        if result["status"] == "PASS":
            print(f"  Status: PASS ({result['passed_cells']}/{result['total_cells']} cells)")
        elif result["status"] == "SKIP":
            print(f"  Status: SKIP - {result['failures'][0]}")
        else:
            print("  Status: FAIL")
            for failure in result["failures"][:5]:
                print(f"    - {failure}")
            if len(result["failures"]) > 5:
                print(f"    ... and {len(result['failures']) - 5} more failures")
            results["overall_status"] = "FAIL"

    return results


# =============================================================================
# REPORT GENERATION (Step 4)
# =============================================================================

def generate_report(
    hash_result: bool,
    pipeline_result: bool | None,
    compare_result: dict[str, Any] | None
) -> str:
    """
    Generate a text report of regression test results.

    Args:
        hash_result: True if hash verification passed
        pipeline_result: True if pipeline ran successfully, None if skipped
        compare_result: Table comparison results, None if skipped

    Returns:
        Formatted report string
    """
    print_header("REGRESSION TEST REPORT")

    lines = [
        "=" * 70,
        "2024 REGRESSION TEST REPORT",
        f"Generated: {datetime.now().isoformat()}",
        "=" * 70,
        "",
    ]

    # Hash verification
    lines.append("INPUT VERIFICATION")
    lines.append("-" * 40)
    lines.append(f"  Frozen inputs: {'PASS' if hash_result else 'FAIL'}")
    lines.append("")

    # Pipeline execution
    lines.append("PIPELINE EXECUTION")
    lines.append("-" * 40)
    if pipeline_result is None:
        lines.append("  Status: SKIPPED")
    elif pipeline_result:
        lines.append("  Status: PASS (all steps completed)")
    else:
        lines.append("  Status: FAIL (pipeline error)")
    lines.append("")

    # Table comparison
    lines.append("TABLE COMPARISON")
    lines.append("-" * 40)
    if compare_result is None:
        lines.append("  Status: SKIPPED")
    else:
        for table_name, result in compare_result.get("tables", {}).items():
            status = result["status"]
            if status == "PASS":
                lines.append(f"  {table_name}: PASS ({result['passed_cells']}/{result['total_cells']} cells)")
            elif status == "SKIP":
                lines.append(f"  {table_name}: SKIP")
            else:
                lines.append(f"  {table_name}: FAIL ({len(result['failures'])} mismatches)")
    lines.append("")

    # Overall result
    lines.append("=" * 70)
    overall_pass = (
        hash_result and
        (pipeline_result is None or pipeline_result) and
        (compare_result is None or compare_result["overall_status"] == "PASS")
    )

    if overall_pass:
        lines.append("OVERALL RESULT: PASS")
        lines.append("")
        lines.append("The 2024 regression test passed. Pipeline outputs match expected values.")
    else:
        lines.append("OVERALL RESULT: FAIL")
        lines.append("")
        lines.append("The 2024 regression test FAILED. Review failures above.")

    lines.append("=" * 70)

    report = "\n".join(lines)
    print(report)
    return report


# =============================================================================
# MAIN ENTRY POINT
# =============================================================================

def main() -> int:
    """
    Main entry point for regression testing.

    Returns:
        Exit code: 0 if all tests passed, 1 if any failed
    """
    parser = argparse.ArgumentParser(
        description="2024 Regression Harness for Buckman Wellfield Pipeline"
    )
    parser.add_argument(
        "--verify",
        action="store_true",
        help="Only verify input hashes (skip pipeline and comparison)"
    )
    parser.add_argument(
        "--compare",
        action="store_true",
        help="Only compare tables (skip pipeline execution)"
    )
    args = parser.parse_args()

    print("=" * 70)
    print("2024 REGRESSION HARNESS")
    print(f"Started: {datetime.now().isoformat()}")
    print("=" * 70)

    # Step 1: Always verify hashes
    hash_result = verify_input_hashes()

    if args.verify:
        # Early exit for hash-only mode
        generate_report(hash_result, None, None)
        return 0 if hash_result else 1

    # Step 2: Run pipeline (unless --compare)
    pipeline_result = None
    if not args.compare:
        if hash_result:
            pipeline_result = run_pipeline_2024()
        else:
            print("\nSkipping pipeline due to hash verification failure.")
            pipeline_result = False

    # Step 3: Compare tables
    compare_result = None
    if hash_result and (args.compare or pipeline_result):
        compare_result = compare_tables()

    # Step 4: Generate report
    generate_report(hash_result, pipeline_result, compare_result)

    # Determine exit code
    overall_pass = (
        hash_result and
        (pipeline_result is None or pipeline_result) and
        (compare_result is None or compare_result["overall_status"] == "PASS")
    )

    return 0 if overall_pass else 1


if __name__ == "__main__":
    sys.exit(main())
